/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include "claves.h"
#include <stdlib.h>

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	init();
	set_value(1, "abcd", 2, 3.0);
    set_value(2, "efgh", 4, 5.0);   
    set_value(3, "ijkl", 6, 7.0);

	char val1[256];
    int val2;
    double val3;

    // Getting values of tuples - error: key doesnt exist.
    get_value(1, val1, &val2, &val3);

	modify_value(2, "qrst", 12, 13.0);

	delete_key(2);

	exist(1);

    exit (0);
}