/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "project3.h"

#define NUM_THREADS 2

// beautiful way to initialize mutex :)
pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t cond = PTHREAD_COND_INITIALIZER;
int sleep_;

void
project_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	int set_value_1_key;
	char *set_value_1_value1;
	int set_value_1_value2;
	double set_value_1_value3;
	enum clnt_stat retval_3;
	response result_3;
	int get_value_1_key;
	enum clnt_stat retval_4;
	int result_4;
	int modify_value_1_key;
	char *modify_value_1_value1;
	int modify_value_1_value2;
	double modify_value_1_value3;
	enum clnt_stat retval_5;
	int result_5;
	int delete_key_1_key;
	enum clnt_stat retval_6;
	int result_6;
	int exist_1_key;
	enum clnt_stat retval_7;
	int result_7;
	int copy_key_1_key1;
	int copy_key_1_key2;

#ifndef	DEBUG
	clnt = clnt_create (host, PROJECT, PROJECT_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = init_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = set_value_1(set_value_1_key, set_value_1_value1, set_value_1_value2, set_value_1_value3, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = get_value_1(get_value_1_key, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = modify_value_1(modify_value_1_key, modify_value_1_value1, modify_value_1_value2, modify_value_1_value3, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = delete_key_1(delete_key_1_key, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = exist_1(exist_1_key, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = copy_key_1(copy_key_1_key1, copy_key_1_key2, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void client_correct();

void client_errors();

int main(int argc, char *argv[]){
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	project_1 (host);


    //-------------------- INIT -------------------- 
    // Initialize the service of elements key, value1, value2 and value3.
    init();

    int j;
	pthread_attr_t attr;
	pthread_t thid[NUM_THREADS];  // number of threads

	pthread_attr_init(&attr);


    if (pthread_create(&thid[0], NULL, (void *) client_correct, NULL) == -1){
        printf("Error al crear los threads\n");
        exit(0);
    }

    pthread_mutex_lock(&lock);
    sleep_ = 1;
    while (sleep_) pthread_cond_wait(&cond, &lock);
    pthread_mutex_unlock(&lock);


    if (pthread_create(&thid[1], NULL, (void *) client_errors, NULL) == -1){
    printf("Error al crear los threads\n");
    exit(0);
    }

    pthread_mutex_lock(&lock);
    sleep_ = 1;
    while (sleep_) pthread_cond_wait(&cond, &lock);
    pthread_mutex_unlock(&lock);

	for (j = 0; j < NUM_THREADS; j++)
		pthread_join(thid[j], NULL);

	pthread_mutex_destroy(&lock);

	exit(0);
}


void client_correct(){

    pthread_mutex_lock(&lock);
    sleep_ = 0;
    pthread_cond_signal(&cond);
    pthread_mutex_unlock(&lock);

    // -------------------- SET_VALUE --------------------
    set_value(1, "abcd", 2, 3.0);
    set_value(2, "efgh", 4, 5.0);   
    set_value(3, "ijkl", 6, 7.0);

    // -------------------- GET_VALUE --------------------
    char val1[256];
    int *val2 = malloc(sizeof(int));  
    double *val3 = malloc(sizeof(double));  
    
    // Getting values of tuples - achieved successfully.
    get_value(1, val1, val2, val3);

    // -------------------- MODIFY_VALUE --------------------
    // Modifying values of tuples - achieved successfully.
    modify_value(2, "mnop", 10, 11.0);

    // -------------------- DELETE_KEY --------------------
    // Deleting tuple with a specific key value - achieved successfully.
    delete_key(1);

    // -------------------- EXIST --------------------
    // Verifying existance of a tuple with a specific key value - achieved successfully.
    exist(2);

    // -------------------- COPY_KEY --------------------
    // Copying the contents from one tuple to another - achieved successfully.
    copy_key(2, 3);
    // Copying the contents from one tuple to another - achieved successfully: key 2 doesnt exist.
    copy_key(3, 4);
}

void client_errors(){

    pthread_mutex_lock(&lock);
    sleep_ = 0;
    pthread_cond_signal(&cond);
    pthread_mutex_unlock(&lock);

    // -------------------- SET_VALUE --------------------
    // Inserting tuples - error: value1 is longer than 256 bytes.
    set_value(4, "The Way the Light Reflects by Richard Siken. The paint doesn’t move the way the light reflects so what’s there to be faithful to? I am faithful to you darling. I say it to the paint. The bird floats in the unfinished sky with nothing to hold it.The man stands the day shines. His insides and his outsides kept apart with an imaginary line— thick and rude and imaginary because there is no separation fallacy of the local body paint on paint. I have my body and you have yours. Believe it if you can. Negative space is silly. When you bang on the wall you have to remember you’re on both sides of it already but go ahead yell at yourself. Some people don’t understand anything. They see the man but not the light they see the field but not the varnish. There is no light in the paint so how can you argue with them? They are probably right anyway. I paint in his face and I paint it out again. There is a question I am afraid to ask: to supply the world with what?", 8, 9.0);

    // Inserting tuples - error: previously existing key.
    set_value(1, "qwert", 56, 74.0);
    
    // -------------------- GET_VALUE --------------------
    char val1[256];
    int *val2 = malloc(sizeof(int));  
    double *val3 = malloc(sizeof(double));  

    // Getting values of tuples - error: key doesnt exist.
    get_value(10, val1, val2, val3);

    free(val2);
    free(val3);
    
    // -------------------- MODIFY_VALUE --------------------
    // Modifying values of tuples - error: key doesnt exist.
    modify_value(10, "qrst", 12, 13.0);
    // Modifying values of tuples - error: value1 longer than 256 bytes.
    modify_value(3, "The Way the Light Reflects by Richard Siken. The paint doesn’t move the way the light reflects so what’s there to be faithful to? I am faithful to you darling. I say it to the paint. The bird floats in the unfinished sky with nothing to hold it.The man stands the day shines. His insides and his outsides kept apart with an imaginary line— thick and rude and imaginary because there is no separation fallacy of the local body paint on paint. I have my body and you have yours. Believe it if you can. Negative space is silly. When you bang on the wall you have to remember you’re on both sides of it already but go ahead yell at yourself. Some people don’t understand anything. They see the man but not the light they see the field but not the varnish. There is no light in the paint so how can you argue with them? They are probably right anyway. I paint in his face and I paint it out again. There is a question I am afraid to ask: to supply the world with what?", 123, 34.5);

    // -------------------- DELETE_KEY --------------------
    // Deleting tuple with a specific key value - error: key doesnt exist.
    delete_key(11);
    
    // -------------------- EXIST --------------------
    // Verifying existance of a tuple with a specific key value - achieved successfully.
    exist(12);
	   
    // -------------------- COPY_KEY --------------------
    // Copying the contents from one tuple to another - error: key 1 doesnt exist.
    copy_key(1, 3);
}
